### ISSUE TITLE
"ExcludeClasses"-settings option no longer valid

### ISSUE THREAD

**Issue by dnepro** [mneuhaus/Famelo.PDF#11]
As of Flow version 3.0.0 the "TYPO3.Flow.object.excludeClasses"-setting is no longer valid and has been replaced by "TYPO3.Flow.object.includeClasses".

I would like to create a PR and fix this by only including "mpdf.*" to the object management.

See [Flow Changelog Entry](http://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartV/ReleaseNotes/300.html#exclude-non-flow-packages-from-object-management-by-default)
See [Flow Issue #103](https://jira.neos.io/browse/FLOW-103)

**Comment by mneuhaus** [comment]
Hey,

yes, please go ahead and make and pull-request for that :)

I'll probably branch off 1.* then and create a 2.0 release for that in order to still support previous flow versions with the 1.* branch.
