### ISSUE TITLE
Exception log entries

### ISSUE THREAD

**Issue by vixe76** [mneuhaus/Famelo.PDF#9]
First of all thx for this nice package. 

The pdf rendering works like a charm and without any exception. But the exception log contains exceptions if the controller action of my package which creates the pdf doesn't have a own template. My workaround is creating an empty template for my controller action.

Can you fix this ... so that no empty template is required?

Best Falk

**Comment by mneuhaus** [comment]
Hey, you're welcome :)

Could you post an example of that Exception?

**Comment by vixe76** [comment]
Sure ... [2016021814272160a161.txt](https://github.com/mneuhaus/Famelo.PDF/files/136322/2016021814272160a161.txt)

**Comment by vixe76** [comment]
Btw. Flow 2.3.11 is in use

**Comment by mneuhaus** [comment]
Hmm, that error doesn't originate in the PDF Package itself, it comes from the controllerAction in which you use the PDF Package. 

Which generator do you use(mpdf, webkit, etc)? 
Which method do you use(send, download, save)?

**Comment by vixe76** [comment]
mpdf with send

**Comment by mneuhaus** [comment]
ah, ok, i'm missing an exit, obviously, so it just continues after the pdf generation currently.
i'll fix that :)

**Comment by mneuhaus** [comment]
https://github.com/mneuhaus/Famelo.PDF/commit/79c3b9b8477062dd0df47fbb394af44192b0a714 should fix this :)

**Comment by mneuhaus** [comment]
and here's the bugfix release: 
https://github.com/mneuhaus/Famelo.PDF/releases/tag/1.0.1

you should be able to update safely with composer now:

```
composer update famelo/pdf
```

**Comment by vixe76** [comment]
insanly fastest fix I've ever seen :-) ... thx ... :+1:

**Comment by mneuhaus** [comment]
you're welcome :)
